spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order_db

  application:
    name: order-service

server:
  port: 8082

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      customerService:
        timeoutDuration: 4s
