server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 3s
