server:
  port: 8082

spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

zipkin:
  base-url: http://localhost:9411
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: product-service
    version: 1.0

logging:
  level:
    root: info
    com.example.productService: debug

product:
  message: "Hello from product-service development profile!"
