server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

product:
  message: "Hello from product-service development profile!"
