server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50

  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 1s

  timelimiter:
    instances:
      userService:
        timeout-duration: 3s

user:
  message: "Hello from user-service dev profile!"
