server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50

  resilience4j:
  retry:
    instances:
      userServiceRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - com.example.userService.exception.ResourceNotFoundException


  timelimiter:
    instances:
      userService:
        timeout-duration: 3s

user:
  message: "Hello from user-service dev profile!"
